export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";

export const FETCH_SUBCATEGORY_REQUEST = "FETCH_SUBCATEGORY_REQUEST";
export const SUBCATEGORY_SUCCESS = "SUBCATEGORY_SUCCESS";
export const SUBCATEGORY_FAILURE = "SUBCATEGORY_FAILURE";
